---
- name: Redistribute JSON configuration files to all hosts
  hosts: all
  become: yes   
  tasks:
    - name: Copy detersettings.json to remote hosts
      copy:
        src: /tmp/CTngV3/def/detersettings.json
        dest: /tmp/CTngV3/def/detersettings.json
        owner: jik18001
        group: jik18001
        mode: '0644'

    - name: Copy deterconfig.json to remote hosts
      copy:
        src: /tmp/CTngV3/def/deterconfig.json
        dest: /tmp/CTngV3/def/deterconfig.json
        owner: jik18001
        group: jik18001
        mode: '0644'
